#!/usr/bin/env python3
"""
Enterprise AI Governance - Model Context Protocol (MCP) Server
=============================================================================
Universal MCP connector that exposes the Enterprise AI Governance Engine
to Claude Desktop, Claude Code, Cursor, Windsurf, VS Code, and Cloud CI/CD.

Allows AI coding assistants to autonomously inspect, govern, audit, and
verify codebases on the developer's behalf.

Protocol: Model Context Protocol (MCP) JSON-RPC 2.0 (v2024-11-05)
Supported Transports: stdio (default), SSE/HTTP (optional)
=============================================================================
"""

import os
import sys
import json
import glob
import re
import contextlib
from pathlib import Path
from typing import Dict, Any, List, Optional

# Ensure package root is in sys.path
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from agents.governance_agent import GovernanceAgent
import yaml

SERVER_NAME = "enterprise-ai-governance-mcp"
SERVER_VERSION = "0.1.0"
PROTOCOL_VERSION = "2024-11-05"

# Copyleft patterns for PR gate check
COPYLEFT_PATTERNS = [
    re.compile(r"(?i)GNU\s+Affero\s+General\s+Public\s+License"),
    re.compile(r"(?i)AGPL-3\.0"),
    re.compile(r"(?i)GNU\s+General\s+Public\s+License\s+v?3"),
    re.compile(r"(?i)GPL-3\.0-only")
]

AI_MARKERS = [
    re.compile(r"(?i)generated by (copilot|chatgpt|claude|gemini|cursor|tabnine)"),
    re.compile(r"(?i)ai-generated-code:?\s*true")
]


# =============================================================================
# TOOL DEFINITIONS (tools/list)
# =============================================================================
TOOLS = [
    {
        "name": "ai_governance_inspect",
        "description": "Deeply inspects an AI codebase, detects ML/RAG/Agent frameworks, PII handling, dangerous tool executions, hardcoded secrets, and infers system archetype and risk tier.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "target_dir": {
                    "type": "string",
                    "description": "Directory path of the project to inspect (defaults to current directory '.')."
                }
            }
        }
    },
    {
        "name": "ai_governance_auto_setup",
        "description": "Autonomously initializes 100% compliant AI governance for any project in under 60 seconds: generates manifest, creates Model & Data Cards, installs pre-commit hooks, installs GitHub Actions PR gate, and resolves policy snapshot.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "target_dir": {
                    "type": "string",
                    "description": "Directory path of the project to onboard (defaults to current directory '.')."
                }
            }
        }
    },
    {
        "name": "ai_governance_audit",
        "description": "Performs a complete compliance audit of a repository against Policy-as-Code standards. Evaluates manifests, policy snapshots, cryptographic integrity seals, secrets, CI gates, and cards. Generates a standalone interactive HTML report.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "target_dir": {
                    "type": "string",
                    "description": "Directory path of the project to audit (defaults to '.')."
                },
                "generate_html": {
                    "type": "boolean",
                    "description": "Whether to generate a standalone HTML report (defaults to true)."
                },
                "output_filename": {
                    "type": "string",
                    "description": "Filename for HTML report (defaults to 'governance-compliance-report.html')."
                }
            }
        }
    },
    {
        "name": "ai_governance_check_pr",
        "description": "Simulates the automated CI/CD Pull Request gate. Scans source code for reciprocal copyleft licenses (GPL/AGPL-3.0), hardcoded API credentials, and unreviewed AI-generated code.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "target_dir": {
                    "type": "string",
                    "description": "Directory path to scan (defaults to '.')."
                }
            }
        }
    },
    {
        "name": "ai_governance_resolve",
        "description": "Executes the deterministic policy snapshot resolver on a project manifest. Calculates active controls across baseline and overlays, and generates an effective-policy-snapshot.json with SHA-256 seal.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "manifest_path": {
                    "type": "string",
                    "description": "Path to ai-project-manifest.yaml."
                },
                "output_path": {
                    "type": "string",
                    "description": "Path where effective-policy-snapshot.json should be saved."
                }
            },
            "required": ["manifest_path"]
        }
    },
    {
        "name": "ai_governance_list_policies",
        "description": "Lists all 16 enterprise AI governance policies (POL-ACC through POL-USE) with their regulatory mappings (EU AI Act, NIST AI RMF, ISO 42001). Can also retrieve the full policy text for a specific policy ID.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "policy_id": {
                    "type": "string",
                    "description": "Optional policy code (e.g., 'POL-SEC', 'POL-IPR', 'POL-DAT', 'POL-FAI') to retrieve its full text."
                }
            }
        }
    },
    {
        "name": "ai_governance_explain_control",
        "description": "Retrieves the full specification and step-by-step remediation advice for any control ID (e.g., 'ORG-CTL-FAI-001', 'ORG-CTL-IPR-003', 'ORG-CTL-SEC-001', 'ORG-CTL-HUM-002').",
        "inputSchema": {
            "type": "object",
            "properties": {
                "control_id": {
                    "type": "string",
                    "description": "The control ID to explain (e.g., 'CTL-FAI-001' or 'ORG-CTL-FAI-001')."
                }
            },
            "required": ["control_id"]
        }
    }
]


# =============================================================================
# RESOURCE DEFINITIONS (resources/list & resources/read)
# =============================================================================
RESOURCES = [
    {
        "uri": "governance://policies",
        "name": "Enterprise AI Governance Policies (Catalog)",
        "description": "Summary of all 16 enterprise AI policies, scopes, and enforcement points.",
        "mimeType": "application/json"
    },
    {
        "uri": "governance://controls",
        "name": "Baseline Controls Inventory",
        "description": "All 60 baseline machine-readable governance controls across 16 domains.",
        "mimeType": "application/json"
    }
]


# =============================================================================
# PROMPT DEFINITIONS (prompts/list & prompts/get)
# =============================================================================
PROMPTS = [
    {
        "name": "audit_ai_repository",
        "description": "Audit an AI codebase against enterprise governance standards and produce an actionable remediation plan.",
        "arguments": [
            {
                "name": "target_dir",
                "description": "Path to the repository to audit.",
                "required": False
            }
        ]
    },
    {
        "name": "onboard_ai_project",
        "description": "Autonomously onboard an AI repository to full enterprise compliance in under 60 seconds.",
        "arguments": [
            {
                "name": "target_dir",
                "description": "Path to the repository to onboard.",
                "required": False
            }
        ]
    }
]


# =============================================================================
# TOOL EXECUTION HANDLERS
# =============================================================================
def handle_inspect(target_dir: str) -> dict:
    agent = GovernanceAgent(target_dir=target_dir)
    findings = agent.scan_codebase()
    arch, risk = agent.infer_archetype_and_risk(findings)
    payload = {
        "status": "success",
        "target_dir": str(agent.target_dir),
        "inferred_archetype": arch,
        "assigned_risk_tier": risk,
        "scanned_files_count": findings["scanned_files"],
        "frameworks_detected": sorted(list(findings["frameworks"])),
        "pii_detected": findings["has_pii"],
        "tools_or_exec_detected": findings["has_tools"],
        "leaked_secrets_count": len(findings.get("leaked_secrets", [])),
        "leaked_secrets": findings.get("leaked_secrets", [])
    }
    return payload


def handle_auto_setup(target_dir: str) -> dict:
    agent = GovernanceAgent(target_dir=target_dir)
    result = agent.auto_setup()
    return {
        "status": "success",
        "target_dir": str(agent.target_dir),
        "message": "Governance onboarding completed successfully.",
        "inferred_archetype": result.get("archetype"),
        "active_controls": result.get("active_controls"),
        "snapshot_integrity_hash": result.get("snapshot_hash"),
        "files_created": [
            "ai-project-manifest.yaml",
            "effective-policy-snapshot.json",
            ".pre-commit-config.yaml",
            ".github/workflows/ai-governance-gate.yaml",
            "governance-cards/model-card.yaml",
            "governance-cards/data-card.yaml",
            "governance-compliance-report.html"
        ]
    }


def handle_audit(target_dir: str, generate_html: bool, output_filename: str) -> dict:
    agent = GovernanceAgent(target_dir=target_dir)
    audit_results = agent.audit(generate_html=generate_html, output_filename=output_filename)
    checks = audit_results.get("checks", [])
    passed = sum(1 for c in checks if c["status"] == "PASS")
    failed = sum(1 for c in checks if c["status"] == "FAIL")
    warn = sum(1 for c in checks if c["status"] == "WARN")
    
    html_report_path = str(agent.target_dir / output_filename) if generate_html else None

    return {
        "status": "success",
        "project_name": audit_results.get("project_name"),
        "project_id": audit_results.get("project_id"),
        "risk_tier": audit_results.get("risk_tier"),
        "archetype": audit_results.get("archetype"),
        "snapshot_hash": audit_results.get("snapshot_hash"),
        "compliance_summary": {
            "total_checks": len(checks),
            "passed": passed,
            "failed": failed,
            "warnings": warn,
            "overall_status": "BLOCKED" if failed > 0 else ("ACTION_REQUIRED" if warn > 0 else "COMPLIANT")
        },
        "checks": checks,
        "html_report_path": html_report_path
    }


def handle_check_pr(target_dir: str) -> dict:
    p = Path(target_dir).resolve()
    source_exts = {".py", ".ts", ".js", ".mjs", ".go", ".java", ".cpp", ".cs", ".sql"}
    
    copyleft_violations = []
    ai_generated_files = []
    secret_violations = []

    secret_regexes = [
        ("OpenAI Secret Key", re.compile(r"sk-[a-zA-Z0-9_\-]{20,}")),
        ("Anthropic API Key", re.compile(r"sk-ant-[a-zA-Z0-9_\-]{20,}")),
        ("HuggingFace Token", re.compile(r"hf_[a-zA-Z0-9]{20,}")),
        ("Generic API Key", re.compile(r"(?i)(api_key|secret_key|access_token)\s*=\s*['\"][a-zA-Z0-9_\-]{20,}['\"]"))
    ]

    for root, dirs, files in os.walk(p):
        dirs[:] = [d for d in dirs if not d.startswith(".") and d not in ["__pycache__", "node_modules", "venv", "env"]]
        for f in files:
            ext = os.path.splitext(f)[1]
            if ext in source_exts:
                fpath = os.path.join(root, f)
                rel_path = os.path.relpath(fpath, p)
                try:
                    with open(fpath, "r", encoding="utf-8", errors="ignore") as file_obj:
                        lines = file_obj.readlines()
                    content = "".join(lines)

                    for pat in COPYLEFT_PATTERNS:
                        if pat.search(content):
                            copyleft_violations.append({
                                "file": rel_path,
                                "violation": "Copyleft license marker detected (ORG-CTL-IPR-003)",
                                "license_match": pat.pattern
                            })
                            break

                    for marker in AI_MARKERS:
                        if marker.search(content):
                            ai_generated_files.append(rel_path)
                            break

                    for line_idx, line in enumerate(lines, 1):
                        if line.strip().startswith("#"):
                            continue
                        for s_name, s_pat in secret_regexes:
                            if s_pat.search(line):
                                secret_violations.append({
                                    "file": rel_path,
                                    "line": line_idx,
                                    "secret_type": s_name
                                })
                                break
                except Exception:
                    continue

    pr_blocked = (len(copyleft_violations) > 0 or len(secret_violations) > 0)
    
    return {
        "status": "success",
        "pr_gate_result": "BLOCKED" if pr_blocked else "PASSED",
        "copyleft_violations_count": len(copyleft_violations),
        "copyleft_violations": copyleft_violations,
        "secret_violations_count": len(secret_violations),
        "secret_violations": secret_violations,
        "ai_generated_files_count": len(ai_generated_files),
        "ai_generated_files": ai_generated_files,
        "enforcement_message": (
            "PR BLOCKED: Copyleft license contamination or hardcoded credentials detected. Merge locked."
            if pr_blocked else
            "PR PASSED: Code is clean of copyleft licenses and hardcoded credentials."
        )
    }


def handle_resolve(manifest_path: str, output_path: Optional[str] = None) -> dict:
    mp = Path(manifest_path).resolve()
    if not mp.exists():
        return {"status": "error", "message": f"Manifest file not found: {manifest_path}"}
    
    op = Path(output_path).resolve() if output_path else mp.parent / "effective-policy-snapshot.json"
    
    resolver_bin = REPO_ROOT / "project-kit" / "resolver" / "resolve.py"
    baseline_dir = REPO_ROOT / "baseline" / "controls"
    overlays_dir = REPO_ROOT / "overlays"

    import subprocess
    cmd = [
        sys.executable, str(resolver_bin),
        "--manifest", str(mp),
        "--baseline-dir", str(baseline_dir),
        "--overlays-dir", str(overlays_dir),
        "--output", str(op)
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        return {"status": "error", "message": f"Resolver failed: {res.stderr}"}
    
    with open(op, "r", encoding="utf-8") as f:
        sdata = json.load(f)

    return {
        "status": "success",
        "snapshot_path": str(op),
        "total_active_controls": sdata.get("total_active_controls"),
        "snapshot_integrity_hash": sdata.get("snapshot_integrity_hash"),
        "project_name": sdata.get("project_name"),
        "risk_tier": sdata.get("risk_tier"),
        "archetype": sdata.get("archetype")
    }


def handle_list_policies(policy_id: Optional[str] = None) -> dict:
    policies_dir = REPO_ROOT / "baseline" / "policies"
    if not policies_dir.exists():
        return {"status": "error", "message": "Policies directory not found"}

    if policy_id:
        clean_id = policy_id.upper().strip()
        matched = list(policies_dir.glob(f"*{clean_id}*.md"))
        if not matched:
            return {"status": "error", "message": f"Policy '{policy_id}' not found"}
        with open(matched[0], "r", encoding="utf-8") as f:
            content = f.read()
        return {
            "status": "success",
            "policy_id": clean_id,
            "filename": matched[0].name,
            "content": content
        }

    catalog = []
    for pf in sorted(policies_dir.glob("*.md")):
        with open(pf, "r", encoding="utf-8") as f:
            first_lines = [f.readline() for _ in range(10)]
        title = "Enterprise Policy"
        for line in first_lines:
            if line.startswith("# "):
                title = line.strip("# \n")
                break
        code = pf.stem.split("-")[1] if "-" in pf.stem else pf.stem
        catalog.append({
            "code": f"POL-{code}",
            "filename": pf.name,
            "title": title
        })

    return {
        "status": "success",
        "total_policies": len(catalog),
        "policies": catalog
    }


def handle_explain_control(control_id: str) -> dict:
    cid = control_id.upper().strip()
    # Normalize ID
    short_cid = cid.replace("ORG-", "")
    
    controls_dir = REPO_ROOT / "baseline" / "controls"
    found_file = None
    for yf in controls_dir.rglob("*.yaml"):
        if short_cid in yf.name.upper() or cid in yf.name.upper():
            found_file = yf
            break

    if not found_file:
        return {"status": "error", "message": f"Control '{control_id}' not found in baseline controls."}

    try:
        with open(found_file, "r", encoding="utf-8") as f:
            cdata = yaml.safe_load(f)
    except Exception as e:
        return {"status": "error", "message": f"Failed to parse control YAML: {e}"}

    remediation_tips = {
        "CTL-FAI-001": "Demographic Disparity / Bias: Ensure the disparate impact ratio across protected groups is >= 0.80. Perform sample reweighting or adversarial debiasing in training.",
        "CTL-IPR-003": "Copyleft License Contamination: AGPL/GPL code cannot be linked in commercial software. Replace with permissive MIT/Apache 2.0 libraries or clean-room reimplementation.",
        "CTL-SEC-001": "Credential Leak: Remove hardcoded API keys and secrets from source code. Migrate to environment variables (e.g., OPENAI_API_KEY) and enable git pre-commit hooks.",
        "CTL-HUM-002": "Clinician / Human Emergency Override: For high-risk decisions, ensure the UI provides an unambiguous manual override button with physician/operator sign-off before execution."
    }

    tip = remediation_tips.get(short_cid, "Ensure required lifecycle cards and configuration files are present in the repository.")

    return {
        "status": "success",
        "control_id": cdata.get("id", cid),
        "name": cdata.get("name"),
        "domain": cdata.get("domain"),
        "risk_tiers": cdata.get("applicable_risk_tiers", []),
        "objective": cdata.get("objective"),
        "normative_obligation": cdata.get("obligation", {}).get("normative_text"),
        "enforcement_point": cdata.get("enforcement", {}).get("point"),
        "remediation_guidance": tip,
        "control_file": str(found_file.relative_to(REPO_ROOT))
    }


# =============================================================================
# JSON-RPC DISPATCHER
# =============================================================================
def handle_request(req: dict) -> dict:
    req_id = req.get("id")
    method = req.get("method")

    # 1. Initialize
    if method == "initialize":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "protocolVersion": PROTOCOL_VERSION,
                "capabilities": {
                    "tools": {},
                    "resources": {},
                    "prompts": {}
                },
                "serverInfo": {
                    "name": SERVER_NAME,
                    "version": SERVER_VERSION
                }
            }
        }

    # 2. Initialized Notification
    elif method == "notifications/initialized":
        return {}

    # 3. Ping
    elif method == "ping":
        return {"jsonrpc": "2.0", "id": req_id, "result": {}}

    # 4. Tools List
    elif method == "tools/list":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "tools": TOOLS
            }
        }

    # 5. Tools Call
    elif method == "tools/call":
        params = req.get("params", {})
        tool_name = params.get("name")
        arguments = params.get("arguments", {})

        try:
            with contextlib.redirect_stdout(sys.stderr):
                if tool_name == "ai_governance_inspect":
                    target_dir = arguments.get("target_dir", ".")
                    res = handle_inspect(target_dir)

                elif tool_name == "ai_governance_auto_setup":
                    target_dir = arguments.get("target_dir", ".")
                    res = handle_auto_setup(target_dir)

                elif tool_name == "ai_governance_audit":
                    target_dir = arguments.get("target_dir", ".")
                    generate_html = arguments.get("generate_html", True)
                    output_filename = arguments.get("output_filename", "governance-compliance-report.html")
                    res = handle_audit(target_dir, generate_html, output_filename)

                elif tool_name == "ai_governance_check_pr":
                    target_dir = arguments.get("target_dir", ".")
                    res = handle_check_pr(target_dir)

                elif tool_name == "ai_governance_resolve":
                    manifest_path = arguments.get("manifest_path")
                    output_path = arguments.get("output_path")
                    res = handle_resolve(manifest_path, output_path)

                elif tool_name == "ai_governance_list_policies":
                    policy_id = arguments.get("policy_id")
                    res = handle_list_policies(policy_id)

                elif tool_name == "ai_governance_explain_control":
                    control_id = arguments.get("control_id")
                    res = handle_explain_control(control_id)

                else:
                    return {
                        "jsonrpc": "2.0",
                        "id": req_id,
                        "error": {"code": -32601, "message": f"Tool '{tool_name}' not found"}
                    }

            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "content": [
                        {
                            "type": "text",
                            "text": json.dumps(res, indent=2) if isinstance(res, dict) else str(res)
                        }
                    ],
                    "isError": (res.get("status") == "error") if isinstance(res, dict) else False
                }
            }

        except Exception as e:
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "content": [{"type": "text", "text": f"Error executing {tool_name}: {str(e)}"}],
                    "isError": True
                }
            }

    # 6. Resources List
    elif method == "resources/list":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "resources": RESOURCES
            }
        }

    # 7. Resources Read
    elif method == "resources/read":
        params = req.get("params", {})
        uri = params.get("uri", "")
        if uri == "governance://policies":
            res = handle_list_policies()
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "contents": [{
                        "uri": uri,
                        "mimeType": "application/json",
                        "text": json.dumps(res, indent=2)
                    }]
                }
            }
        elif uri == "governance://controls":
            c_dir = REPO_ROOT / "baseline" / "controls"
            c_list = [f.name for f in c_dir.rglob("*.yaml")]
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "contents": [{
                        "uri": uri,
                        "mimeType": "application/json",
                        "text": json.dumps({"total_controls": len(c_list), "controls": sorted(c_list)}, indent=2)
                    }]
                }
            }
        elif uri.startswith("governance://policy/"):
            pid = uri.split("/")[-1]
            res = handle_list_policies(pid)
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "contents": [{
                        "uri": uri,
                        "mimeType": "text/markdown",
                        "text": res.get("content", f"Policy {pid} not found")
                    }]
                }
            }
        else:
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "error": {"code": -32602, "message": f"Unknown resource URI: {uri}"}
            }

    # 8. Prompts List
    elif method == "prompts/list":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "prompts": PROMPTS
            }
        }

    # 9. Prompts Get
    elif method == "prompts/get":
        params = req.get("params", {})
        pname = params.get("name")
        args = params.get("arguments", {})
        tdir = args.get("target_dir", ".")

        if pname == "audit_ai_repository":
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "description": "Audit an AI repository",
                    "messages": [
                        {
                            "role": "user",
                            "content": {
                                "type": "text",
                                "text": f"Please perform an AI governance audit on the repository at '{tdir}'. Run ai_governance_audit, report any failed checks or compliance gaps, and guide me on how to remediate them."
                            }
                        }
                    ]
                }
            }
        elif pname == "onboard_ai_project":
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {
                    "description": "Onboard an AI project",
                    "messages": [
                        {
                            "role": "user",
                            "content": {
                                "type": "text",
                                "text": f"Please onboard the project at '{tdir}' using ai_governance_auto_setup. Inspect its architecture, generate its manifest and lifecycle cards, install the pre-commit and PR CI/CD gates, and summarize what was accomplished."
                            }
                        }
                    ]
                }
            }
        else:
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "error": {"code": -32602, "message": f"Unknown prompt: {pname}"}
            }

    # Unhandled method
    return {
        "jsonrpc": "2.0",
        "id": req_id,
        "error": {"code": -32601, "message": f"Method '{method}' not implemented"}
    }


# =============================================================================
# MAIN SERVER LOOP (stdio transport)
# =============================================================================
def main():
    """Reads JSON-RPC messages from stdin and writes responses to stdout."""
    # Ensure stdout/stdin are unbuffered utf-8
    sys.stdin.reconfigure(encoding="utf-8")
    sys.stdout.reconfigure(encoding="utf-8")

    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
            resp = handle_request(req)
            if resp:  # Notifications don't require responses
                sys.stdout.write(json.dumps(resp) + "\n")
                sys.stdout.flush()
        except Exception as e:
            err_resp = {
                "jsonrpc": "2.0",
                "id": None,
                "error": {"code": -32603, "message": str(e)}
            }
            sys.stdout.write(json.dumps(err_resp) + "\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
